language: csharp
mono: none
dotnet: 2.0.3

before_install:
  - sudo apt-get install libgdiplus -y

install: 
- bash ./cicd.sh install

script:
- bash ./cicd.sh build
- bash ./cicd.sh test

deploy:
  provider: script
  #skip_cleanup: true
  script: bash ./cicd.sh deploy
  on:
    branch: release  
    tags: true
